# Generated by Django 4.0.2 on 2022-02-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=200)),
                ('product_desc', models.TextField()),
                ('prod_img', models.ImageField(blank=True, upload_to='products/photos')),
            ],
        ),
    ]
